# Pipeline: IoT Sensor Data Processor
# Description: Read sensor data from stdin, add lineage metadata, batch and output
# Components: stdin → processors → stdout (batched every 10s)
#
# Usage:
#   # Stream from file
#   cat sensor-data.jsonl | expanso-edge run pipelines/sensor-processor.yaml
#
#   # Stream directly from generator
#   ./sensor-gen/sensor-gen -d 60s | expanso-edge run pipelines/sensor-processor.yaml
#
#   # With custom batch settings
#   cat data.jsonl | BATCH_SIZE=500 BATCH_PERIOD=5s expanso-edge run pipelines/sensor-processor.yaml
#
# Configuration:
#   - BATCH_SIZE: Number of records per batch (default: 1000)
#   - BATCH_PERIOD: Time window for batching (default: 10s)
#   - EDGE_NODE_ID: Identifier for this edge node (default: from hostname)

input:
  label: "sensor_stdin_reader"
  stdin:
    codec: lines

pipeline:
  processors:
    # Parse JSON and add lineage metadata
    - mapping: |
        root = this

        # Add lineage information
        root.lineage = {
          "edge_node": env("EDGE_NODE_ID").or(env("HOSTNAME")).or("unknown"),
          "pipeline": "sensor-processor",
          "pipeline_version": "1.0.0",
          "ingested_at": now().ts_format("2006-01-02T15:04:05.000Z"),
          "source_file": env("INPUT_FILE").or("output.jsonl")
        }

        # Data quality checks - flag anomalies
        let is_anomaly = false
        let anomaly_reasons = []

        # Check for out-of-range values based on sensor type
        let is_anomaly = if this.type == "pressure" && this.value > 1500 { true } else { $is_anomaly }
        let anomaly_reasons = if this.type == "pressure" && this.value > 1500 { $anomaly_reasons.append("pressure_exceeded") } else { $anomaly_reasons }

        let is_anomaly = if this.type == "temperature" && (this.value > 180 || this.value < -20) { true } else { $is_anomaly }
        let anomaly_reasons = if this.type == "temperature" && (this.value > 180 || this.value < -20) { $anomaly_reasons.append("temperature_out_of_range") } else { $anomaly_reasons }

        let is_anomaly = if this.type == "flow_rate" && this.value > 50000 { true } else { $is_anomaly }
        let anomaly_reasons = if this.type == "flow_rate" && this.value > 50000 { $anomaly_reasons.append("flow_rate_exceeded") } else { $anomaly_reasons }

        let is_anomaly = if this.quality_score < 0.8 { true } else { $is_anomaly }
        let anomaly_reasons = if this.quality_score < 0.8 { $anomaly_reasons.append("low_quality_score") } else { $anomaly_reasons }

        root.data_quality = {
          "is_anomaly": $is_anomaly,
          "anomaly_reasons": $anomaly_reasons,
          "validated": true
        }

output:
  label: "batched_stdout"
  stdout:
    codec: lines
  batching:
    count: ${BATCH_SIZE:1000}
    period: "${BATCH_PERIOD:10s}"
    processors:
      # Create a summary for each batch
      - archive:
          format: json_array
      - mapping: |
          let records = this
          let count = $records.length()
          let anomaly_count = $records.filter(r -> r.data_quality.is_anomaly == true).length()

          root = {
            "batch_summary": {
              "record_count": $count,
              "anomaly_count": $anomaly_count,
              "anomaly_rate": if $count > 0 { ($anomaly_count / $count * 100).round() } else { 0 },
              "batch_time": now().ts_format("2006-01-02T15:04:05.000Z"),
              "edge_node": env("EDGE_NODE_ID").or(env("HOSTNAME")).or("unknown")
            },
            "records": $records
          }
