# Pipeline: IoT Sensor Data Enricher (Streaming)
# Description: Read sensor data from stdin, add lineage, validate, and stream to stdout
# Components: stdin → processors → stdout
#
# This is a simpler streaming version - each record is processed and output immediately.
# Use sensor-processor.yaml for batched output with summaries.
#
# Usage:
#   cat sensor-data.jsonl | expanso-edge run pipelines/sensor-enricher.yaml
#   ./sensor-gen/sensor-gen -d 10s | expanso-edge run pipelines/sensor-enricher.yaml
#
# Configuration:
#   - EDGE_NODE_ID: Identifier for this edge node (default: from hostname)

input:
  label: "sensor_stdin_reader"
  stdin:
    codec: lines

pipeline:
  processors:
    - mapping: |
        root = this

        # Add lineage metadata
        root.lineage = {
          "edge_node": env("EDGE_NODE_ID").or(env("HOSTNAME")).or("unknown"),
          "pipeline": "sensor-enricher",
          "ingested_at": now().ts_format("2006-01-02T15:04:05.000Z")
        }

        # Simple validation flag
        root.validated = true
        root.is_anomaly = this.alert_level == "high" || this.alert_level == "medium" || this.quality_score < 0.85

output:
  stdout:
    codec: lines
